### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by 0xMukesh** [Kira272921/snowball-bot#1]
Create contributing guidelines which mentions the steps of 
- How to contribute to this repository
- Clone the repository
- Make a PR

**Comment by krishguptadev** [comment]
Can I work on this?

**Comment by Tejas-Teju** [comment]
@Kira272921, Can I take this one? this will be a great opportunity for me to learn on how to setup guidelines and maybe I need help with this.

**Comment by 0xMukesh** [comment]
Sure! 😄

**Comment by unnikrishnan2002** [comment]
Is someone on in this issue else I would like to take this up @Kira272921

**Comment by Tejas-Teju** [comment]
@unnikrishnan2002, please go ahead and work on it.

**Comment by 0xMukesh** [comment]
> Is someone on in this issue else I would like to take this up @Kira272921

Hey, you could work on this :D
