### ISSUE TITLE
Create Pull Request template

### ISSUE THREAD

**Issue by 0xMukesh** [Kira272921/snowball-bot#2]
A pull request template is needed

> Here are the docs on `How to create a Pull Request template` 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by krishguptadev** [comment]
Can I work on this?

**Comment by avneesh0612** [comment]
Can I take up this one?

**Comment by 0xMukesh** [comment]
> Can I take up this one?

Seems that you have created a PR already 👀
